foreground #e9e2d4
background #16130b
cursor     #dfc56d
selection_foreground #3b2f00
selection_background #dfc56d

color0  #110e07
color1  #ffb4ab
color2  #d3c6a1
color3  #abcfb0
color4  #dfc56d
color5  #2e4e36
color6  #4f462a
color7  #e9e2d4
color8  #979080
color9  #ffb4ab
color10 #d3c6a1
color11 #abcfb0
color12 #dfc56d
color13 #2e4e36
color14 #4f462a
color15 #e9e2d4
