-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:AOC 27G2G3 0x0000038D",
  mode = "1920x1080@165.00",
  position = "2149x2023",
  scale = 1,
  vrr = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:BOE 0x0C06",
  mode = "2560x1600@240.00",
  position = "-411x2408",
  scale = 1,
  vrr = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Samsung Electric Company SAMSUNG",
  mode = "3840x2160@60.00",
  position = "4069x798",
  scale = 1,
  vrr = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})
